### ISSUE TITLE
review model input

### ISSUE THREAD

**Issue by tonyjongyoonan** [tonyjongyoonan/enpoisson#8]
please review/verify/be wary of model input prior to usage:

input: list of tuples -- (from_fen, last_16_moves, curr_color)

feedback will be cached so we do not re-query when a user goes back and forth

**Comment by nlao1** [comment]
Yeah, i think the way to pass it on is to make it a json with the following fields:
```python
    fen: str
    last_16_moves: List[str]
    is_white_move: bool
```
So first two seem fine, I just made the thing a bool but if you think it should be a char/string lmk

**Comment by tonyjongyoonan** [comment]
sgtm
